# 项目启动端口
server:
  address: :2002
  # debug模式
  model: debug
  # release模式
  #model:release

# 数据库配置
db:
  dialects: mysql
  host: 10.130.41.246
  port: 3306
  db: jx
  username: root
  password: Admin!@123
  charset: utf8
  # 最大空闲数
  maxIdle: 50
  # 最大连接数
  maxOpen: 150

# redis配置
redis:
  address: 10.130.41.7:3900
  password: zxJZt7PidfT

# 图片地址和ip
imageSettings:
  # 本地磁盘地址
  uploadDir: /tmp/upload/
  # 本地ip地址
  imageHost: http://localhost:2002

# log日志配置
log:
  path: /tmp
  name: sys
  # 输出到控制台
  model: file
  # 输出到文件
  # model: file
